In [64]:
import numpy as np

In [66]:
np.__version__

'1.26.4'

In [68]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

CREATING LIST

In [71]:
list = [0,1,2,3,4,5,6,7,8]
list

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [73]:
type(list)

list

BELOW CODE WE ARE CONVERTING LIST TO ARRAY

In [76]:
arr = np.array(list)

In [78]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [80]:
type(arr)

numpy.ndarray

In [82]:
type(list)

list

In [84]:
np. # press tab to get all inbuild functions

SyntaxError: invalid syntax (3589933145.py, line 1)

In [86]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.arange(5.)

array([0., 1., 2., 3., 4.])

In [90]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [92]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [94]:
np.arange(20,10) # always 1st arg < 2nd arg

array([], dtype=int32)

In [96]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [98]:
np.arange(10,10)

array([], dtype=int32)

In [100]:
np.arange(10,30,5) #1st arg start from 10 ,2nd arg ends below 30 and 3rd arg 5 step count  b/w elements in the array

array([10, 15, 20, 25])

In [102]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [104]:
np.arange(10,30,5,3) # max arg it take up to three

TypeError: Cannot interpret '3' as a data type

In [106]:
np.zeros(10) # parameter tunning # it gives float 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [108]:
np.zeros(5, dtype=int) # hyperparameter tunning # ti gives integer

array([0, 0, 0, 0, 0])

In [110]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [112]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [114]:
zero = np.zeros([2,2])
print(zero)
print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [116]:
np.zeros((2,10)) # by default left side is row and right side is column

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [118]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [120]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [122]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [124]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [126]:
np.ones(3)

array([1., 1., 1.])

In [128]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [130]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [132]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [134]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [136]:
np.t

AttributeError: module 'numpy' has no attribute 't'

In [138]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [140]:
np.three((2,3))

AttributeError: module 'numpy' has no attribute 'three'

In [142]:
rand(3,2)

NameError: name 'rand' is not defined

In [144]:
random.rand(3,2)

NameError: name 'random' is not defined

In [146]:
np.random.rand(3,2) #np or numpy is a package random is a module rand is a function

array([[0.40338066, 0.57069528],
       [0.13838259, 0.52964851],
       [0.65880871, 0.57706305]])

In [148]:
np.rand(5)

AttributeError: module 'numpy' has no attribute 'rand'

In [150]:
np.random.rand(5)

array([0.11162161, 0.99809138, 0.4540557 , 0.07565363, 0.93153722])

In [152]:
np.random.rand(3,5)

array([[0.93634747, 0.19705447, 0.32812506, 0.85046664, 0.05790052],
       [0.39361407, 0.24395312, 0.29430803, 0.74466166, 0.3693966 ],
       [0.00350291, 0.35583635, 0.95642848, 0.10708519, 0.27829027]])

In [154]:
np.random.randint(4,6) # either 4 or 5

5

In [156]:
np.random.randint(2,20,4) #generate 4 random integer in blw 2 to 20

array([4, 5, 7, 8])

In [158]:
np.random.randint(0,1) # 1 is exclusive the output is always 0

0

30 th may 

In [161]:
np.random.randint(1,20,10)

array([ 2,  5, 11, 16,  4, 13, 19, 15,  1, 16])

In [163]:
np.random.randint(2,20,(10,10)) # generate the elements from 2-20 with 10x10 matrix

array([[10, 19,  5,  9, 19, 13,  9,  2, 19,  3],
       [19,  7, 19,  6, 17, 13, 19,  7, 17, 14],
       [14, 18, 18,  5,  6, 11, 12, 16, 15,  6],
       [17, 19, 11, 11, 11, 11, 19, 13,  3, 14],
       [ 2, 12,  2,  9,  7, 15, 16,  3, 17, 14],
       [13,  8, 15,  9, 14, 13, 13,  3, 11, 11],
       [ 4,  3,  7, 10,  9, 12,  4,  3, 14, 15],
       [ 5,  9, 14,  6,  6, 14,  2, 14,  7,  2],
       [14, 16,  5, 15, 16,  2,  3,  6,  5, 17],
       [11,  4, 14, 17, 10, 17, 16, 19,  5, 18]])

In [165]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [167]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [169]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [171]:
np.arange(1,13).reshape(4,5)

ValueError: cannot reshape array of size 12 into shape (4,5)

In [173]:
np.arange(1,13).reshape(2,3)

ValueError: cannot reshape array of size 12 into shape (2,3)

In [175]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [177]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

SLICING IN MATRIX

In [180]:
b = np.random.randint(10,20,(5,4))

In [182]:
b

array([[18, 15, 12, 16],
       [17, 14, 18, 11],
       [12, 14, 11, 14],
       [17, 12, 15, 10],
       [19, 10, 18, 19]])

In [184]:
type(b)

numpy.ndarray

In [186]:
b

array([[18, 15, 12, 16],
       [17, 14, 18, 11],
       [12, 14, 11, 14],
       [17, 12, 15, 10],
       [19, 10, 18, 19]])

In [188]:
b[:]

array([[18, 15, 12, 16],
       [17, 14, 18, 11],
       [12, 14, 11, 14],
       [17, 12, 15, 10],
       [19, 10, 18, 19]])

In [190]:
b[1:3] # ti will print only rows

array([[17, 14, 18, 11],
       [12, 14, 11, 14]])

In [192]:
b

array([[18, 15, 12, 16],
       [17, 14, 18, 11],
       [12, 14, 11, 14],
       [17, 12, 15, 10],
       [19, 10, 18, 19]])

In [194]:
b[1,3]# it will print specific value from the matrix

11

In [196]:
b[2,3]

14

In [198]:
b[1,-1]

11

In [200]:
b[2:3]

array([[12, 14, 11, 14]])

In [202]:
b[0:-2]

array([[18, 15, 12, 16],
       [17, 14, 18, 11],
       [12, 14, 11, 14]])

In [204]:
b[0,2]

12

In [206]:
b

array([[18, 15, 12, 16],
       [17, 14, 18, 11],
       [12, 14, 11, 14],
       [17, 12, 15, 10],
       [19, 10, 18, 19]])

In [208]:
b[-5,3]

16

In [210]:
b[-5,-3]

15

In [212]:
b[-4,2]

18

Numpy Operations

In [215]:
arr2 =np.random.randint(0,100,(10,10))

In [217]:
arr2

array([[81,  6, 87, 41, 25, 33,  9, 79, 48, 62],
       [35, 78, 19, 25, 22, 86,  0, 16, 46, 56],
       [34, 84,  3, 24, 34, 62, 81, 65, 79, 38],
       [47, 58, 33, 12, 66,  9, 54, 73, 85, 20],
       [16, 49, 76, 96, 80, 89, 84, 25, 98, 72],
       [96, 47, 51, 68, 40, 52, 15, 38, 32, 45],
       [ 1, 27, 23, 35, 43, 22, 93, 80, 66, 44],
       [61, 31, 87,  1, 11, 39, 76, 16, 26, 25],
       [58, 22, 26, 66, 40, 66, 31, 16, 76, 95],
       [97, 94, 24,  2,  7, 90,  2, 30, 91, 46]])

In [232]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [234]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [236]:
arr[:4]

array([0, 1, 2, 3])

In [238]:
arr[:1]

array([0])

In [256]:
arr1 = np.array(8)
arr1

array(8)

In [258]:
arr2[:]

array([[81,  6, 87, 41, 25, 33,  9, 79, 48, 62],
       [35, 78, 19, 25, 22, 86,  0, 16, 46, 56],
       [34, 84,  3, 24, 34, 62, 81, 65, 79, 38],
       [47, 58, 33, 12, 66,  9, 54, 73, 85, 20],
       [16, 49, 76, 96, 80, 89, 84, 25, 98, 72],
       [96, 47, 51, 68, 40, 52, 15, 38, 32, 45],
       [ 1, 27, 23, 35, 43, 22, 93, 80, 66, 44],
       [61, 31, 87,  1, 11, 39, 76, 16, 26, 25],
       [58, 22, 26, 66, 40, 66, 31, 16, 76, 95],
       [97, 94, 24,  2,  7, 90,  2, 30, 91, 46]])

In [260]:
arr2[0:5]

array([[81,  6, 87, 41, 25, 33,  9, 79, 48, 62],
       [35, 78, 19, 25, 22, 86,  0, 16, 46, 56],
       [34, 84,  3, 24, 34, 62, 81, 65, 79, 38],
       [47, 58, 33, 12, 66,  9, 54, 73, 85, 20],
       [16, 49, 76, 96, 80, 89, 84, 25, 98, 72]])

In [262]:
arr2

array([[81,  6, 87, 41, 25, 33,  9, 79, 48, 62],
       [35, 78, 19, 25, 22, 86,  0, 16, 46, 56],
       [34, 84,  3, 24, 34, 62, 81, 65, 79, 38],
       [47, 58, 33, 12, 66,  9, 54, 73, 85, 20],
       [16, 49, 76, 96, 80, 89, 84, 25, 98, 72],
       [96, 47, 51, 68, 40, 52, 15, 38, 32, 45],
       [ 1, 27, 23, 35, 43, 22, 93, 80, 66, 44],
       [61, 31, 87,  1, 11, 39, 76, 16, 26, 25],
       [58, 22, 26, 66, 40, 66, 31, 16, 76, 95],
       [97, 94, 24,  2,  7, 90,  2, 30, 91, 46]])

In [264]:
arr2[1,2]

19

In [266]:
arr2[-5,5]

52

In [268]:
arr2[-5,-5]

52

In [272]:
arr2[-1,-2]

91

In [274]:
arr2

array([[81,  6, 87, 41, 25, 33,  9, 79, 48, 62],
       [35, 78, 19, 25, 22, 86,  0, 16, 46, 56],
       [34, 84,  3, 24, 34, 62, 81, 65, 79, 38],
       [47, 58, 33, 12, 66,  9, 54, 73, 85, 20],
       [16, 49, 76, 96, 80, 89, 84, 25, 98, 72],
       [96, 47, 51, 68, 40, 52, 15, 38, 32, 45],
       [ 1, 27, 23, 35, 43, 22, 93, 80, 66, 44],
       [61, 31, 87,  1, 11, 39, 76, 16, 26, 25],
       [58, 22, 26, 66, 40, 66, 31, 16, 76, 95],
       [97, 94, 24,  2,  7, 90,  2, 30, 91, 46]])

In [276]:
arr2[::-1]

array([[97, 94, 24,  2,  7, 90,  2, 30, 91, 46],
       [58, 22, 26, 66, 40, 66, 31, 16, 76, 95],
       [61, 31, 87,  1, 11, 39, 76, 16, 26, 25],
       [ 1, 27, 23, 35, 43, 22, 93, 80, 66, 44],
       [96, 47, 51, 68, 40, 52, 15, 38, 32, 45],
       [16, 49, 76, 96, 80, 89, 84, 25, 98, 72],
       [47, 58, 33, 12, 66,  9, 54, 73, 85, 20],
       [34, 84,  3, 24, 34, 62, 81, 65, 79, 38],
       [35, 78, 19, 25, 22, 86,  0, 16, 46, 56],
       [81,  6, 87, 41, 25, 33,  9, 79, 48, 62]])

In [278]:
arr2[::-2]

array([[97, 94, 24,  2,  7, 90,  2, 30, 91, 46],
       [61, 31, 87,  1, 11, 39, 76, 16, 26, 25],
       [96, 47, 51, 68, 40, 52, 15, 38, 32, 45],
       [47, 58, 33, 12, 66,  9, 54, 73, 85, 20],
       [35, 78, 19, 25, 22, 86,  0, 16, 46, 56]])

In [288]:
arr2[::3]

array([[81,  6, 87, 41, 25, 33,  9, 79, 48, 62],
       [47, 58, 33, 12, 66,  9, 54, 73, 85, 20],
       [ 1, 27, 23, 35, 43, 22, 93, 80, 66, 44],
       [97, 94, 24,  2,  7, 90,  2, 30, 91, 46]])

In [290]:
arr2

array([[81,  6, 87, 41, 25, 33,  9, 79, 48, 62],
       [35, 78, 19, 25, 22, 86,  0, 16, 46, 56],
       [34, 84,  3, 24, 34, 62, 81, 65, 79, 38],
       [47, 58, 33, 12, 66,  9, 54, 73, 85, 20],
       [16, 49, 76, 96, 80, 89, 84, 25, 98, 72],
       [96, 47, 51, 68, 40, 52, 15, 38, 32, 45],
       [ 1, 27, 23, 35, 43, 22, 93, 80, 66, 44],
       [61, 31, 87,  1, 11, 39, 76, 16, 26, 25],
       [58, 22, 26, 66, 40, 66, 31, 16, 76, 95],
       [97, 94, 24,  2,  7, 90,  2, 30, 91, 46]])

In [286]:
arr2[::-3]

array([[97, 94, 24,  2,  7, 90,  2, 30, 91, 46],
       [ 1, 27, 23, 35, 43, 22, 93, 80, 66, 44],
       [47, 58, 33, 12, 66,  9, 54, 73, 85, 20],
       [81,  6, 87, 41, 25, 33,  9, 79, 48, 62]])

In [294]:
arr2.max()

98

In [296]:
arr2.min()

0

In [298]:
arr2.mean()

47.7

In [300]:
arr2.median

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [302]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

In [306]:
from numpy import *
b = arr2
print(b)

[[81  6 87 41 25 33  9 79 48 62]
 [35 78 19 25 22 86  0 16 46 56]
 [34 84  3 24 34 62 81 65 79 38]
 [47 58 33 12 66  9 54 73 85 20]
 [16 49 76 96 80 89 84 25 98 72]
 [96 47 51 68 40 52 15 38 32 45]
 [ 1 27 23 35 43 22 93 80 66 44]
 [61 31 87  1 11 39 76 16 26 25]
 [58 22 26 66 40 66 31 16 76 95]
 [97 94 24  2  7 90  2 30 91 46]]


In [308]:
arr2

array([[81,  6, 87, 41, 25, 33,  9, 79, 48, 62],
       [35, 78, 19, 25, 22, 86,  0, 16, 46, 56],
       [34, 84,  3, 24, 34, 62, 81, 65, 79, 38],
       [47, 58, 33, 12, 66,  9, 54, 73, 85, 20],
       [16, 49, 76, 96, 80, 89, 84, 25, 98, 72],
       [96, 47, 51, 68, 40, 52, 15, 38, 32, 45],
       [ 1, 27, 23, 35, 43, 22, 93, 80, 66, 44],
       [61, 31, 87,  1, 11, 39, 76, 16, 26, 25],
       [58, 22, 26, 66, 40, 66, 31, 16, 76, 95],
       [97, 94, 24,  2,  7, 90,  2, 30, 91, 46]])

In [314]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [316]:
arr.reshape(9,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [318]:
arr.reshape(3,3,order='C') #elements are stored row-wise

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [320]:
arr.reshape(3,3,order='F')#elements are stored column-wise

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [322]:
arr.reshape(3,3,order='A')# elements are stored based on the original array's memory layout.

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [324]:
arr.reshape(3,3,order='K')

ValueError: order 'K' is not permitted for reshaping

In [326]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Indexing

In [329]:
mat = np.arange(0,100).reshape(10,10)

In [331]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [333]:
row = 4
col = 5

In [335]:
row

4

In [337]:
col

5

In [339]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [341]:
mat[row,col]

45

In [343]:
mat[4,5]

45

In [345]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [347]:
col = 6

In [349]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [351]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [353]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [355]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [357]:
row

4

In [359]:
col

6

In [361]:
mat[:, :col]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55],
       [60, 61, 62, 63, 64, 65],
       [70, 71, 72, 73, 74, 75],
       [80, 81, 82, 83, 84, 85],
       [90, 91, 92, 93, 94, 95]])

In [363]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [365]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [367]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [369]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [371]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [373]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [375]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [377]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [379]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [381]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [383]:
mat[:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [385]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [387]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [389]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [391]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [393]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [395]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [397]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [401]:
mat[2:6,2:4] #2:6 indicate row part and 2:4 indicate coloum part

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [403]:
mat[2:6,3:4]

array([[23],
       [33],
       [43],
       [53]])

In [406]:
mat[0,1]

1

In [408]:
mat[1,6]

16

In [410]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [412]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [414]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [416]:
mat[3,5]

35

In [418]:
mat[1:2,2:4]

array([[12, 13]])

In [420]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [424]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [426]:
mat[2:3,4:5]

array([[24]])

MASKING

In [429]:
mat # we also called ir]t as a filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [431]:
id(mat)

2036014299056

In [433]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [435]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [437]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [439]:
mat[mat==50]

array([50])

In [441]:
a = mat[mat<50]

In [443]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [445]:
b = mat[mat>50]

In [447]:
b

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [449]:
c = mat[mat>=50]

In [451]:
c

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [453]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [455]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [457]:
b

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [459]:
c

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])