COMPLETE NUMPY inbuild functions

In [1]:
import numpy as np

1.Array Creation Function

In [4]:
# Create an arry from a list
a = np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [5]:
#creat an array with evenly spaced values
b = np.array([0,10,2])#Value from o to 10 with 2 step gap
print("Array b:", b)

Array b: [ 0 10  2]


In [6]:
# Creat an array with linearly spaced values
c = np.linspace(0,1,5)# 5 value devenly spaced b/w 0 to 1
print('Array c:', c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [7]:
# Creat an array filled with zeros
d = np.zeros((2,3)) # 2x3 array of zeros
print("Array d:",d)
print('Array d:\n',d)

Array d: [[0. 0. 0.]
 [0. 0. 0.]]
Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#create an array filled with ones
e = np.ones((2,3)) # 2x3 array of ones
print("Array e:\n" ,e)

Array e:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# Create an identity matrix 
f = np.eye(4) #4x4 identity matrix
print("Identity matrix f:\n", f)#Return a 2-D array with ones on the diagonal and zeros elsewhere.

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2.Array Manipulation Function

In [11]:
# Reshape an array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(3,1)) #Reshape to 1x3
print("Reshaped array:\n",reshaped)

Reshaped array:
 [[1]
 [2]
 [3]]


In [12]:
# Reshape an array
a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (1, 3))  # Reshape to 1x3
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]]


In [13]:
#flattern an array
f1 = np.array([[1,2],[3,4]])#Flattern to 1d array
flattened = np.ravel(f1)
print("Flatterned array:",flattened)

Flatterned array: [1 2 3 4]


In [14]:
#Transpose an array
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)# Trasnpose the array
print("Transposed array:\n",transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [15]:
# Stack arrays vertically
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


3.Mathematical Functions

In [21]:
#add +2 to the each elements present an array
g = np.array([1,2,3,4])
added = np.add(g,2)#add 2 to each element
print("Added 2 to g:",added)

Added 2 to g: [3 4 5 6]


In [29]:
# square each element
squared = np.power(g,2)
print("Squared g:", squared)

Squared g: [ 1  4  9 16]


In [31]:
#square root of each element
sqrt_val = np.sqrt(g)
print("Square root of g:",sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [39]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [43]:
# Dot product of two arrays
a2 = np.array([1,2,3,4])
dot_product = np.dot(a2,g) # dot product of a and g
print("Dot product of a nad g:", dot_product)

Dot product of a nad g: 30


In [45]:
a3 = np.array([1,2,3])
dot_product = np.dot(a1,a) # dot product of a and g 
print("Dot product od a1 and a:", dot_product)

Dot product od a1 and a: 14


4.Statistical Function

In [48]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print('Mean of S:',mean)

Mean of S: 2.5


In [50]:
#standard deviation of an araay 
std_dev = np.std(s)
print("Standard deviation od S :",std_dev)

Standard deviation od S : 1.118033988749895


In [52]:
#minimun element of an array
minimum = np.min(s)
print("Min of s:",minimum)

Min of s: 1


In [54]:
#Maximum element of an array 
maximum = np.max(s)
print("Max of S:",maximum)

Max of S: 4


5.Linear Algerbra Function 

In [57]:
#b create a matrix
matrix = np.array([[1,2],[3,4]])

In [59]:
# Determinant of  a matrix 
determinant = np.linalg.det(matrix)
print("Determinant of matrix:", determinant)

Determinant of matrix: -2.0000000000000004


In [65]:
# Inverse of a matrix
inverse = np.linalg.inv(matrix)
print("Inverse of martix:\n",inverse)

Inverse of martix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


6 . Random Sampling Functions

In [72]:
#Generate random values between o and 1 
random_val = np.random.rand(3)# #  Array of 3 ramdom values between 0 and 1
print("Ramdom values:", random_val)

Ramdom values: [0.37687776 0.44883577 0.05806477]


In [74]:
# set seed for reproducibility 
np.random.seed(0)
# Generate random values between 0 and 1
random_vals = np.random.rand(3)
print("Random values :",random_vals)

Random values : [0.5488135  0.71518937 0.60276338]


In [80]:
# generate ramdom integers 
rand_ints = np.random.randint(0,10, size=5)#random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [2 4 7 6 8]


In [86]:
#set seed for reproducility 
np.random.seed(0) # how tomes you run you get same random numbers

#Generate random integers 
rand_ints = np.random.randint(0,10,size=5)#random integers between 0 and 10
print("Random integers:",rand_ints)

Random integers: [5 0 3 3 7]


7.Boolean & Logical Functions

In [91]:
# Check if all elements are true 
# All
logical_test = np.array([True,False,True])
all_true = np.all(logical_test)
print("All element True:", all_true)

All element True: False


In [93]:
logical_test = np.array([False,False,False])
all_true = np.all(logical_test)
print("All element True:", all_true)

All element True: False


In [95]:
logical_test = np.array([True,True,True])
all_true = np.all(logical_test)
print("All element True:", all_true)

All element True: True


In [97]:
# Check if any elements are True
# any
any_true = np.any(logical_test) # Check if any are true
print("Any element True:", any_true)

Any element True: True


8.Set operations

In [102]:
# Intersection of two arrays 
set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,6])
intersection = np.intersect1d(set_a,set_b)
print('Union of a and b:',intersection)

Union of a and b: [3 4]


#union of two arrays
union = np.union1d(set_a,set_b)
print("Union of and b:", union)

9.Array Attribute Function

In [116]:
#array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int32


10.Other functions

In [119]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [121]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 12


In [123]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
